# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow():
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(330, 379)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(4.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(0, 0, 330, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_result.setFont(font)
        self.label_result.setStyleSheet("background-color: rgb(0, 255, 187);\n"
"color: rgb(0, 46, 77);")
        self.label_result.setObjectName("label_result")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 60, 90, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(0, 46, 77);\n"
"color: rgb( 0, 255, 187);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(90, 60, 90, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: rgb(0, 46, 77);\n"
"color: rgb( 0, 255, 187);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(180, 60, 90, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: rgb(0, 46, 77);\n"
"color: rgb( 0, 255, 187);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(90, 140, 90, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(0, 46, 77);\n"
"color: rgb( 0, 255, 187);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 140, 90, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(0, 46, 77);\n"
"color: rgb( 0, 255, 187);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(180, 140, 90, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(0, 46, 77);\n"
"color: rgb( 0, 255, 187);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 220, 90, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 46, 77);\n"
"color: rgb( 0, 255, 187);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 220, 90, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("background-color: rgb(0, 46, 77);\n"
"color: rgb( 0, 255, 187);")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 220, 90, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(0, 46, 77);\n"
"color: rgb( 0, 255, 187);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_result = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_result.setGeometry(QtCore.QRect(90, 300, 181, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_result.setFont(font)
        self.pushButton_result.setStyleSheet("background-color: rgb(0, 255, 187);\n"
"color: rgb(0, 46, 77);")
        self.pushButton_result.setObjectName("pushButton_result")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(0, 300, 90, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("background-color: rgb(0, 46, 77);\n"
"color: rgb( 0, 255, 187);")
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_plus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plus.setGeometry(QtCore.QRect(270, 60, 60, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_plus.setFont(font)
        self.pushButton_plus.setStyleSheet("background-color: rgb(0, 46, 77);\n"
"color: rgb( 0, 255, 187);")
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.pushButton_minus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_minus.setGeometry(QtCore.QRect(270, 140, 60, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_minus.setFont(font)
        self.pushButton_minus.setStyleSheet("background-color: rgb(0, 46, 77);\n"
"color: rgb( 0, 255, 187);")
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.pushButton_multi = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_multi.setGeometry(QtCore.QRect(270, 220, 60, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_multi.setFont(font)
        self.pushButton_multi.setStyleSheet("background-color: rgb(0, 46, 77);\n"
"color: rgb( 0, 255, 187);")
        self.pushButton_multi.setObjectName("pushButton_multi")
        self.pushButton_divis = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_divis.setGeometry(QtCore.QRect(270, 300, 60, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_divis.setFont(font)
        self.pushButton_divis.setStyleSheet("background-color: rgb(0, 46, 77);\n"
"color: rgb( 0, 255, 187);")
        self.pushButton_divis.setObjectName("pushButton_divis")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

        self.is_equel = False




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.label_result.setText(_translate("MainWindow", "0"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_result.setText(_translate("MainWindow", "="))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_plus.setText(_translate("MainWindow", "+"))
        self.pushButton_minus.setText(_translate("MainWindow", "-"))
        self.pushButton_multi.setText(_translate("MainWindow", "*"))
        self.pushButton_divis.setText(_translate("MainWindow", "/"))

    def add_functions(self):
        self.pushButton_0.clicked.connect(lambda: self.write_number((self.pushButton_0.text())))
        self.pushButton_1.clicked.connect(lambda: self.write_number((self.pushButton_1.text())))
        self.pushButton_2.clicked.connect(lambda: self.write_number((self.pushButton_2.text())))
        self.pushButton_3.clicked.connect(lambda: self.write_number((self.pushButton_3.text())))
        self.pushButton_4.clicked.connect(lambda: self.write_number((self.pushButton_4.text())))
        self.pushButton_5.clicked.connect(lambda: self.write_number((self.pushButton_5.text())))
        self.pushButton_6.clicked.connect(lambda: self.write_number((self.pushButton_6.text())))
        self.pushButton_7.clicked.connect(lambda: self.write_number((self.pushButton_7.text())))
        self.pushButton_8.clicked.connect(lambda: self.write_number((self.pushButton_8.text())))
        self.pushButton_9.clicked.connect(lambda: self.write_number((self.pushButton_9.text())))
        self.pushButton_plus.clicked.connect(lambda: self.write_number((self.pushButton_plus.text())))
        self.pushButton_minus.clicked.connect(lambda: self.write_number((self.pushButton_minus.text())))
        self.pushButton_multi.clicked.connect(lambda: self.write_number((self.pushButton_multi.text())))
        self.pushButton_divis.clicked.connect(lambda: self.write_number((self.pushButton_divis.text())))
        self.pushButton_result.clicked.connect(self.result)

    def write_number(self,number):
        if self.label_result.text()=='0' or self.is_equel:
            self.label_result.setText(number)
            self.is_equel=False
        else:
            self.label_result.setText(self.label_result.text()+number)

    def result(self):
        if not self.is_equel:
            res=eval(self.label_result.text())
            self.label_result.setText(str(res))
            self.is_equel=True
        else:
            error=QMessageBox()
            error.setWindowTitle('Error')
            error.setText('Error of clicking')
            error.setIcon(QMessageBox.blockSignals)
            error.setStandardButtons(QMessageBox.Ok|QMessageBox.Cancel)
            error.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
